name: Deployment

on:
  push:
    branches: 
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set output
      id: vars
      run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}

    - name: Deploy the api to the dav Backend
      uses: dav-apps/dav-api-deployment-action@master
      with:
        base-url: ${{ secrets.API_BASE_URL }}
        api-id: ${{ secrets.API_ID }}
        auth: ${{ secrets.AUTH }}
        branch: ${{ steps.vars.outputs.branch_name }}